### ISSUE TITLE
can't find /api/things route neither in the server templates nor the generated app

### ISSUE THREAD

**Issue by sallespro** [michaelkrone/generator-material-app#1]
hi, i am exploring the generator and could not fully experiment the api. i have just been able to authenticate users but not have a clear understanding of all the possible /api calls.

**Comment by michaelkrone** [comment]
Hallo @sallespro. Thank you for your interest in my project. I will update the sources this weekend. The api/things route is an unused artifact that will be removed in the next version. The documentation will also be updated (the README and the client docs will be generated as well).
Stay tuned.

**Comment by michaelkrone** [comment]
The sources have been updated. The things route has been removed. The README will receive a comprehensive update soon.

Some things to try:

Simply accept all standard answers (hit enter all the time):
```
yo material-app
yo material-app:api cat
yo material-app:apiroute cat
gulp build
npm start
```

**Comment by michaelkrone** [comment]
The README has been updated as well
