### ISSUE TITLE
MongoDB connection refused

### ISSUE THREAD

**Issue by kiempoturner** [michaelkrone/generator-material-app#10]
I got this error :

Database Error:  { [MongoError: connect ECONNREFUSED] name: 'MongoError', message: 'connect ECONNREFUSED' }

What is the meaning of this

**Comment by merqurio** [comment]
That means that you don't have a mongo database installation working on your computer. You should [install mongo first](https://www.mongodb.org/downloads), and then make sure [you can run it](http://docs.mongodb.org/manual/tutorial/getting-started/). Once you do that, run this app.

**Comment by kiempoturner** [comment]
Okay sorry for the trouble, I will try it asap. Thank You

**Comment by michaelkrone** [comment]
I will close this issue, please reopen if there are any problems with the connection.
Thank you @merqurio for your fast and comprehensive response.

**Comment by julia-bougaev** [comment]
I am sorry but I have the same problem. I've installed mongo. I cannot figure out where is db itself in your application, should I create it myself (if so in which directory)? In the index.js file I cannot find setting for config.mongo.uri and config.mongo.options. Am I missing something?
