### ISSUE TITLE
Styles issue

### ISSUE THREAD

**Issue by panagorn** [michaelkrone/generator-material-app#20]
Hello i have a problem with the styles. 
![untitled](https://cloud.githubusercontent.com/assets/8356922/9527275/c0932df4-4cf6-11e5-9bed-7f41657f3d54.png)

**Comment by michaelkrone** [comment]
Hi.
Looks like the list-image directive is not working. Do you have any errors in the console?

There will be an update on the Material Version tomorrow evening. The issue will be obsolete then, I think.

**Comment by michaelkrone** [comment]
Could you please check if the Sass is compiled for the directive too?

**Comment by panagorn** [comment]
no console errors. How i can check if the sass is compiled?

**Comment by michaelkrone** [comment]
I see - your on windows, right?
This should be fixed with the latest version, see Issue Nr. #18, fixed by @petersandor 
I just published 0.1.4 on npm, I recommend to try the latest version, just run npm install to get it.

I am just working on a layout update and plan to release tomorrow.

**Comment by panagorn** [comment]
ok thank you

**Comment by michaelkrone** [comment]
Just reinstall the generator by running

    npm install -g generator-material-app

and create a new application. Did that work for you?

**Comment by panagorn** [comment]
No is not working

**Comment by michaelkrone** [comment]
Are there any errors when running

    yo material-app
    gulp

**Comment by panagorn** [comment]
i am getting this error on yo material-app
![untitled](https://cloud.githubusercontent.com/assets/8356922/9544810/49784fc4-4d8c-11e5-99b3-399102e26d46.png)

**Comment by michaelkrone** [comment]
This looks like a permission problem to me. Could you grant read/write permissions to C:\Users\panayoitis\AppData\Roaming\npm-cache?

Sorry, I have no experience with node development under Windows.

**Comment by panagorn** [comment]
I set the permissions. Now i dont get an error but the style is the same. No changes at all

**Comment by donchoko** [comment]
I had the same issue with styles. I didn't have ruby or sass installed, and gulp build was showing some errors related. I installed ruby ([Download Ruby](http://rubyinstaller.org/downloads/)) and installed sass <code>gem install sass</code> and finally do <code>gulp build</code> and styles should work fine.

**Comment by stupidisum** [comment]
Did you run `gulp build` before `npm start` ?

**Comment by HelloJasonZhang** [comment]
I also met this issue on Window, Run gulp styles command, ut there is no app.css to be generated in the client\styles directory.

**Comment by stupidisum** [comment]
Are you Chinese?
Recommand: 不要用windows开发!
Maybe you can try the new windows10 bash for linux?

**Comment by Stupidism** [comment]
I have a friend came up with this issue, too. I think what @donchoko said is the right answer

**Comment by HelloJasonZhang** [comment]
Thank @stupidisum , Windows is not friend.
