### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Malusia** [michaelkrone/generator-material-app#22]
Hey, can you add a Licence to your project?

**Comment by michaelkrone** [comment]
Hi @Malusia.

There is a LICENSE file in the root directory: https://github.com/michaelkrone/generator-material-app/blob/master/LICENSE

If you plan to use this project it is worth waiting for the upcomming Version 1.0.0, which will use the latest material version and makes heavy use of generator composition.

**Comment by Malusia** [comment]
Thanks a lot!
