### ISSUE TITLE
i can not edit users

### ISSUE THREAD

**Issue by ruizhit** [michaelkrone/generator-material-app#26]
Go to edit test user
<img width="1271" alt="screen shot 2015-10-22 at 15 20 39" src="https://cloud.githubusercontent.com/assets/7987506/10677241/bf9aa782-78d0-11e5-91b4-eb2d8607c56f.png">
_
Modified role
and click save
<img width="1275" alt="screen shot 2015-10-22 at 15 21 02" src="https://cloud.githubusercontent.com/assets/7987506/10677259/da6f15de-78d0-11e5-9091-43be1a990bf6.png">

Terminal error

<img width="843" alt="screen shot 2015-10-22 at 15 21 33" src="https://cloud.githubusercontent.com/assets/7987506/10678162/34564928-78d6-11e5-85dd-dd4aabe9ef2a.png">

generator-material-app/myapp/server/lib/controllers/param.controller.js:116:12

**Comment by michaelkrone** [comment]
Hi @ruizhit.
Thank you, I will have a look at this.

**Comment by ricsard** [comment]
I also saw this bug, and it was because of invalid usage of 'this'

**Comment by michaelkrone** [comment]
Hey @ricsard,

would you create a pull request for this error?

**Comment by amirmo** [comment]
+1.
I tried @ricsard solution and it works just fine.

**Comment by michaelkrone** [comment]
Should be closed with #38
