### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by zanjs** [michaelkrone/generator-material-app#27]
julauddeMacBook-Pro:app julaud$ npm start

> app@0.0.0 start /Users/www/npm/app
> node bin/server.js

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:9001
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:450:9)
    at process._tickDomainCallback (node.js:397:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 start: `node bin/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.0.0 start script 'node bin/server.js'.
npm ERR! This is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/www/npm/app/npm-debug.log
julauddeMacBook-Pro:app julaud$

**Comment by michaelkrone** [comment]
Hi @zanjs.
```Error: listen EADDRINUSE 0.0.0.0:9001```
This means that there is already an application running on port 9001. Simply switch to another port by editing the ```port``` property in the server/config/index.js file or start the application using a ```PORT``` environment variable:
```PORT=9002 node ./bin/server.js```

**Comment by zanjs** [comment]
thinks ！ Let me try！
