### ISSUE TITLE
An erro when start the app

### ISSUE THREAD

**Issue by julia-bougaev** [michaelkrone/generator-material-app#28]
How can I run the application? Using npm start I get

0 info it worked if it ends with ok
 1 verbose cli [ 'c:\Program Files (x86)\nodejs\node.exe',
 1 verbose cli 'c:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js',
 1 verbose cli 'start' ]
 2 info using npm@2.11.3
 3 info using node@v0.12.7
 4 verbose stack Error: ENOENT, open 'c:\Test\package.json'
 4 verbose stack at Error (native)
 5 verbose cwd c:\Test
 6 error Windows_NT 6.3.9600
 7 error argv "c:\Program Files (x86)\nodejs\node.exe" "c:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "start"
 8 error node v0.12.7
 9 error npm v2.11.3
 10 error path c:\Test\package.json
 11 error code ENOENT
 12 error errno -4058
 13 error enoent ENOENT, open 'c:\Test\package.json'
 13 error enoent This is most likely not a problem with npm itself
 13 error enoent and is related to npm not being able to find a file.
 14 verbose exit [ -4058, true ]

**Comment by suman28** [comment]
i am also getting the same error..pls help

**Comment by michaelkrone** [comment]
Hi.

Did you call ```npm start``` in the root folder of the generated app (where the package.json is located)?

**Comment by julia-bougaev** [comment]
Thanks, it works.
