### ISSUE TITLE
reopen for #10

### ISSUE THREAD

**Issue by julia-bougaev** [michaelkrone/generator-material-app#29]
I am sorry but I have the same problem. I've installed mongo and run it. I put db in some folder which is outside the app folder. But in the index.js file I cannot find setting for config.mongo.uri and config.mongo.options. Am I missing something?

Thanks

**Comment by michaelkrone** [comment]
Hi @julia-bougaev.

What does 'I put db in some folder which is outside the app folder' mean, and what error do you get (can you paste the error message here)?

**Comment by julia-bougaev** [comment]
Sorry for the disturbance. After I resolved my issue with starting the app everything is working now. Thanks

**Comment by michaelkrone** [comment]
Fine, no problem.
