### ISSUE TITLE
Installing on mac error

### ISSUE THREAD

**Issue by julia-bougaev** [michaelkrone/generator-material-app#30]
93844 error Darwin 13.4.0
93845 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
93846 error node v5.0.0
93847 error npm  v3.3.10
93848 error code ELIFECYCLE
93849 error app@0.0.0 postinstall: `node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update`
93849 error Exit status 1
93850 error Failed at the app@0.0.0 postinstall script 'node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update'.
93850 error Make sure you have the latest version of node.js and npm installed.
93850 error If you do, this is most likely a problem with the app package,
93850 error not with npm itself.
93850 error Tell the author that this fails on your system:
93850 error     node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update
93850 error You can get their info via:
93850 error     npm owner ls app
93850 error There is likely additional logging output above.
93851 verbose exit [ 1, true ]

**Comment by michaelkrone** [comment]
Hey @julia-bougaev.
To make the npm install work, simply remove this line: https://github.com/michaelkrone/generator-material-app/blob/master/generators/app/templates/package.json#L35 from the package json, it simply updates the webdriver sources. I will have a look at this later.

**Comment by julia-bougaev** [comment]
Thanks, I'll try
