### ISSUE TITLE
Yeoman and Gulp errors on Ubuntu 15.04

### ISSUE THREAD

**Issue by AndrewBarfield** [michaelkrone/generator-material-app#31]
## yo material-app output:

104201 verbose stack Error: app@0.0.0 postinstall: `node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update`
104201 verbose stack Exit status 1
104201 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
104201 verbose stack     at emitTwo (events.js:87:13)
104201 verbose stack     at EventEmitter.emit (events.js:172:7)
104201 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
104201 verbose stack     at emitTwo (events.js:87:13)
104201 verbose stack     at ChildProcess.emit (events.js:172:7)
104201 verbose stack     at maybeClose (internal/child_process.js:818:16)
104201 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
104202 verbose pkgid app@0.0.0
104203 verbose cwd /home/drew/testing/app
104204 error Linux 3.19.0-28-generic
104205 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
104206 error node v4.2.1
104207 error npm  v3.3.10
104208 error code ELIFECYCLE
104209 error app@0.0.0 postinstall: `node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update`
104209 error Exit status 1
104210 error Failed at the app@0.0.0 postinstall script 'node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update'.
104210 error Make sure you have the latest version of node.js and npm installed.
104210 error If you do, this is most likely a problem with the app package,
104210 error not with npm itself.
104210 error Tell the author that this fails on your system:
104210 error     node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update
104210 error You can get their info via:
104210 error     npm owner ls app
104210 error There is likely additional logging output above.
104211 verbose exit [ 1, true ]

## gulp build output:

/home/drew/testing/app/node_modules/main-bower-files/lib/index.js:81
            throw error;
            ^

Error: Bower components directory does not exist at /home/drew/testing/app/client/bower_components
    at Error (native)
    at module.exports (/home/drew/testing/app/node_modules/main-bower-files/lib/index.js:76:17)
    at Object.<anonymous> (/home/drew/testing/app/gulp/config.js:11:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/drew/testing/app/gulpfile.js:11:12)
drew@drew-ubuntu:~/testing/app$

**Comment by lexholden** [comment]
+1 same problem.

**Comment by AndrewBarfield** [comment]
I ended-up buying this for $1.59 (2.20 Australian):
http://www.bossable.com/1231/material-design-meanjs/

If you changed all the version numbers in "package.json" and "bower.json" it will run on Node.js 4.x and 5.x with a few other simple adjustments.

**Comment by michaelkrone** [comment]
This seems to be related to the flat directory structure of npm 3.  Just remove the postinstall script from the package.json or adjust the path to the protactor webdriver binary when using npm 3. I will remove the postinstall (replace with a gulp task) in an updated version.
