### ISSUE TITLE
Generation error

### ISSUE THREAD

**Issue by GeekEdem** [michaelkrone/generator-material-app#55]
After 
`yo generator-material-app` :

> Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo material-app
 # Configuration
? Shall I scaffold out a JWT authentication (with users and stuff)? Yes
? Would you like to use socket.io? Yes

Error:
>npm WARN Failed to parse json
npm WARN Unexpected token ',' at 28:30
npm WARN                "passport-local": "~0.1.6",,
npm WARN                                           ^
npm WARN File: /home/chihray/PROjects/generator-material-app/package.json
npm WARN generator-material-app No description
npm WARN generator-material-app No repository field.
npm WARN generator-material-app No README data
npm WARN generator-material-app No license field.

I remove `,` from `package.json` and enter this command: `bower install & npm install`:
> sh: 1: ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager: not found
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! generator-material-app@0.0.0 postinstall: `./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the generator-material-app@0.0.0 postinstall script './node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the generator-material-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs generator-material-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls generator-material-app
npm ERR! There is likely additional logging output above.

This is because location webdriver-manager is not correct: 
`find node_modules/ -name 'webdriver-manager'`
> node_modules/.bin/webdriver-manager
> node_modules/protractor/bin/webdriver-manager

Fix it, please =)

**Comment by michaelkrone** [comment]
Hi @GeekEdem,

this should be fixed now, can you try with 0.2.1 please?

**Comment by TejasCMehta** [comment]
@michaelkrone, Thanks for quick update!! I was just facing this problem 10mins ago and now  
`npm install -g generator-material-app` works perfectly fine after your update.

BTW, great work!!  

Cheers!

**Comment by michaelkrone** [comment]
Thanks @GeekEdem, so I will close this issue.
