### ISSUE TITLE
Documentation about client model feature

### ISSUE THREAD

**Issue by michaelkrone** [michaelkrone/generator-material-app#56]

**Comment by Stupidism** [comment]
Not finished yet!
About: Client side model definition for form inputs and info display.
But I can make a task list for documents of done jobs here first.

## ModelDefinitions factory
- [ ] ModelDefinitions(nestedDefinition) RETURN modelDefinition
  - [ ] Param: nestedDefinition, mongoose-like nested definition of front-end model
  - [ ] returns: modelDefinition, array of propDefintions
  
  with util functions
  - [ ] .extend(modelDefinition): deep extend another modelDefinition
  - [ ] .flat: flat mongoose-like nestedDefinition to propDefinitions
  - [ ] .display: get displayValue of one prop of model

## ModelInputGroup directive
- [ ] ModelInputGroup receives a modelDefinition and an ngModel, map propDefinitions to list of ModelInput directive.
- [ ] ModelInput receives a propDefinition and an ngModel, display different kinds of inputs depending on type of propDefinition.
- [ ] types
  - [ ] input: default type
  - [ ] select: use md-select
  
  planning: 
  - [ ] date
  - [ ] file
  - [ ] quantity: number and unit
  - [ ] textarea
  - [ ] switch
  - [ ] radio
  - [ ] checkbox

**Comment by michaelkrone** [comment]
We could generate some standard form validations for this, I will have a look at it.

**Comment by Stupidism** [comment]
Yes, validations is in plan!

**Comment by Stupidism** [comment]
These are detail of fulfill and doesn't need docs for now.
doc of how to use modelDefinition #83
