### ISSUE TITLE
Some errors with angular-animate.js ?

### ISSUE THREAD

**Issue by merqurio** [michaelkrone/generator-material-app#6]
Hi !

I just created an instance with the generator, but it seems that there is a problem with animate.js. The browser reports: 
```
TypeError: Cannot read property '' of undefined
    at lookup (angular-animate.js:617)
    at animationRunner (angular-animate.js:681)
    at performAnimation (angular-animate.js:1284)
    at angular-animate.js:959
    at angular-animate.js:539
    at Scope.$get.Scope.$digest (angular.js:15352)
    at Scope.$get.Scope.$apply (angular.js:15570)
    at bootstrapApply (angular.js:1582)
    at Object.invoke (angular.js:4379)
    at doBootstrap (angular.js:1580)
```

I'm going to try with a different version of angular-animate and or a different angular version.
Everything else seems to work nicely

thanks and I hope this helps  :smile:

**Comment by michaelkrone** [comment]
Thank you, I will have a look at this.

**Comment by michaelkrone** [comment]
This is due to a version conflict with angular 1.4 and angular-material master, which depends on 1.3. For now the latest available stable material version is used: 0.8.3. I would like to keep Angular 1.4 since it is stable soon. There are still some minor errors relating angular-animate but the app will work fine.

To use the AngularJS 1.3 branch modify the bower.json versions and resolutions. The app should work with 1.3 too, but I have not tested it.

Closed with 1ad8342220ba6eadd47bc207755fc3ee2aa3e31d

**Comment by dbrooks75** [comment]
I was having same issue.  Angular-animate 1.3.15 was installed, while the rest of the angular components were 1.4.*.  I got the app working by changing bower.json to:

{
  "name": "myApp",
  "version": "0.0.1",
  "dependencies": {
    "angular": ">=1.4.*",
    "angular-resource": ">=1.4.*",
    "angular-cookies": ">=1.4.*",
    "angular-sanitize": ">=1.4.*",
    "angular-messages": ">=1.4.*",
    "angular-ui-router": "latest",
    "material-design-icons": ">=1.0.1",
    "lodash": "~2.4.1",
    "angular-material": "master",
    "angular-socket-io": "~0.6.0",
    "angular-i18n": "~1.3.14",
    "angular-moment": "~0.9.0",
    "angular-animate": "1.4.0-rc.0",
    "angular-aria": "1.4.0-rc.0",
    "angular-mocks": "1.4.0-rc.0",
    "angular-scenario": "1.4.0-rc.0"
  },
  "devDependencies": {
    "angular-mocks": "1.4.0-rc.0",
    "angular-scenario": "1.4.0-rc.0",
    "should": "shouldjs/should.js#~4.4.1"
  },
  "resolutions": {
    "angular": ">=1.4.*"
  }
}

**Comment by michaelkrone** [comment]
Hello @dbrooks75. The latest version 0.1.2 should force the installation of angular-animate 1.4. I hope angular-material updates to 1.4 soon.

Thank you for your input.

**Comment by merqurio** [comment]
Thanks @dbrooks75 , I'll check it, this is definitively an awesome project
