### ISSUE TITLE
newly generated code shows right side blank area, not full width listing

### ISSUE THREAD

**Issue by TejasCMehta** [michaelkrone/generator-material-app#60]
![image](https://cloud.githubusercontent.com/assets/5519037/15497859/674c3ecc-21ba-11e6-8bd9-f7e887816a78.png)

**Comment by TejasCMehta** [comment]
Ok, what I did to resolve this issue is

`//var sass = require('gulp-ruby-sass');`
`var sass    = require('gulp-sass');`

I am working on windows and do not want to install ruby so I used `gulp-sass` package to make css from scss. 

Hope someone can take a help from this.

Cheers!!

**Comment by michaelkrone** [comment]
@TejasCMehta 
Glad you got it running. We should move to 'plain sass' insted of ruby sass in general.
So I close this issue, if you stumble on any problems please open a new issue.
