### ISSUE TITLE
webdriveer-manger update error on new generator run - windows 8.1 pc

### ISSUE THREAD

**Issue by TejasCMehta** [michaelkrone/generator-material-app#61]
![image](https://cloud.githubusercontent.com/assets/5519037/15498002/0a9ffed8-21bb-11e6-95c3-19c77a0582bc.png)

**Comment by Stupidism** [comment]
Did you solve this yourself? 
I noticed you opened another issue showing you have your app generated already.

**Comment by Stupidism** [comment]
look at this #55

**Comment by TejasCMehta** [comment]
yes, initially I was not above run the command `npm install generator-material-app` command but then @michaelkrone  updated the repo and I was able to run the command, but then in the end this error came.

**Comment by michaelkrone** [comment]
This seems to be a known problem with gulp-protractor and windows. I will try to fix it by using the protractor binary instead, there is evidence on the web this helps.

**Comment by michaelkrone** [comment]
Need to solve #66 before I can publish a new version. To try if it works you might checkout the  fix/webdriver-manager branch and do a `npm link` in the cloned directory. Then you are able to call `yo material-app` with the fix applied, or just wait till the merging is done.

**Comment by michaelkrone** [comment]
@TejasCMehta 
Even better: Do a `npm install --save-dev protractor` and in you package.json change the "postinstall" line to `"postinstall": "node ./node_modules/protractor/bin/webdriver-manager update",`

**Comment by TejasCMehta** [comment]
![image](https://cloud.githubusercontent.com/assets/5519037/15552300/661d1940-22d7-11e6-91c9-42f14038b044.png)

**Comment by TejasCMehta** [comment]
changing to  `"postinstall": "node ./node_modules/protractor/bin/webdriver-manager update"`
resolves the issue! 
Thanks!!
