### ISSUE TITLE
gulp watch and livereload

### ISSUE THREAD

**Issue by TejasCMehta** [michaelkrone/generator-material-app#64]
how can we add gulp watch and livereload so do not need to run npm start after any file change?

**Comment by michaelkrone** [comment]
Just run `gulp watch` in a terminal. A browser window will open with browser sync active. It will refresh the page if any file is changed. If a scss file is changed it will get compiled.

I will close this Issue, post here if you have any questions.

**Comment by TejasCMehta** [comment]
`gulp watch` gave me below message

![image](https://cloud.githubusercontent.com/assets/5519037/15534911/c217890a-2288-11e6-91a4-28588a82e08d.png)

**Comment by Stupidism** [comment]
I have this error, too. Let me look at this.
`gulp watch` outputs 

``` bash
materialApp started server on ip 0.0.0.0 on port 9001, in test mode
```

while `npm start` outputs

```
materialApp started server on ip 0.0.0.0 on port 9001, in development mode
```

I think this is the reason

No, it's not...

**Comment by Stupidism** [comment]
Haha, I found the bug.

**Comment by Stupidism** [comment]
This is because gulp watched too many files.

Change your `gulp/config.js` `src.client.js` to

```
      [
        '!client/app/**/*.spec.js',
        '!client/app/**/*.mock.js',
        'client/app/**/*.js'
      ]
```

and `src.html` to

```
    [
      'client/app/**/*.html',
      'client/index.html'
    ]
```

**Comment by TejasCMehta** [comment]
Hey @stupidisum thanks for quick fix !!

How can I take this latest fix in my working application?

**Comment by TejasCMehta** [comment]
#79

**Comment by Stupidism** [comment]
As I said above, change your own gulp/config.js.

**Comment by TejasCMehta** [comment]
It  works great now, after your said changes!! :)

Many thanks!
