### ISSUE TITLE
socket.io config and lib will break npm start 

### ISSUE THREAD

**Issue by jeveloper** [michaelkrone/generator-material-app#7]
In the case of responding "n" to socket.io , app.js will still have code loading socket.io config and module and it won't work obviously since they are missing.

**Comment by michaelkrone** [comment]
Hello @jeveloper. Thank you for your issue report.
Can you explain the issue in more detail?
What do you mean with responding "n"?

**Comment by michaelkrone** [comment]
Sorry @jeveloper, I understand now. You are right, optional socket.io support is not completed yet. It does not need much to be done but I am preparing a switch to the new Angular router, so I removed optional socket.io support in version 0.1.2. This should close this Issue, but I am not satisfied with the solution. Optional socket.io support is definitely on my list.

Closed with 1ad8342220ba6eadd47bc207755fc3ee2aa3e31d
