### ISSUE TITLE
Can I consider this as a production ready code?

### ISSUE THREAD

**Issue by TejasCMehta** [michaelkrone/generator-material-app#77]
This is awesome generator, and I am feeling great by coming to this repo. Couple of thing I am still not able to identify.

I am trying to evaluate this generator and dev mode it works fine but still not sure that code is ready for production server or not.

Even there is not any easy command to run code in production mode?

`gulp watch` shows mongoose connection error.
`NODE_ENV=production npm run seed` how this can be run on windows system?
How to deploy on azure/heroku?

such type of things are missing in ReadMe.

**Comment by Stupidism** [comment]
`gulp watch` is not working now. @michaelkrone #79 

`NODE_ENV=production npm run seed` is for production to create init root user.
When development you don't need this.
But you can emulate production with this command in your computer.

Your server environment NODE_ENV should be production already.
You should find some place to config your server to run `npm run seed` after launch.
or you can ssh into your server and run `NODE_ENV=production npm run seed` directly.

**Comment by TejasCMehta** [comment]
I run `set  NODE_ENV=production` on windows command prompt and it set env mode= production, gulp build work fine and indicates that it runs in production mode on npm start, but it do not able to find npm run seed command.

`npm run seed` is not found in local npm folder. how this works? will go inside seed.js file?

**Comment by Stupidism** [comment]
Sorry, I forgot npm run seed is not in 0.2.2. 

For now, you have two options:
1. You can modify your `server/config/seed.js` to seed a root user in production.
2. You can use develop branch first and wait for our next release

**Comment by TejasCMehta** [comment]
I am eager to grab your next stable release, please give me estimate how long should I wait?

**Comment by Stupidism** [comment]
Sorry, I'm an undergrade now. I'm busy with my Graduation Project. I joined this repo a few days ago. So what I'm contributing now is what I've done in my own project. Maybe after I finish my graduation project in early June, I will focus on next stable release but not fancy new and half features now.

This project is what my company is using now. So I'll continue to contribute after that. Don't worry.

The owner is busy himself. I don't know how much time he will spend in this, @michaelkrone

**Comment by michaelkrone** [comment]
I am on a conference today, but the weekend is reserved for doing a Material Update and alining the master/published Version with develop.

Then the production env should be work with npm Version.

**Comment by TejasCMehta** [comment]
Thanks @stupidisum @michaelkrone

**Comment by TejasCMehta** [comment]
Should we bother about below warnings while doing npm install from git bash on windows system as Admin rights ?

![image](https://cloud.githubusercontent.com/assets/5519037/15569164/685e004a-234d-11e6-8f7e-9c585c43ad5c.png)

**Comment by Stupidism** [comment]
some old dependencies caused this. I have some of these warnings, too.
Don't ask unrelated questions in closed issue. 
Open another issure if you do have a question.

**Comment by michaelkrone** [comment]
@TejasCMehta
Hi, please do not use the app in production of it can be accessed via the Internet. The packaged jwt version has a known security issue. Please wait for #44 to be closed.
