### ISSUE TITLE
Please release one stable version with all the fixes which are pending in PR.

### ISSUE THREAD

**Issue by TejasCMehta** [michaelkrone/generator-material-app#78]
I think most of the code is getting fixed on daily basis so how can I get that latest fixes in my current code, and once you release that how can I upgrade my code to that?

**Comment by Stupidism** [comment]
If you don't mind some half-work. Try 

```
git clone this-repo
git checkout develop
npm link
```

then your global generator-material-app will link to this local project

**Comment by TejasCMehta** [comment]
sure, I will try this and let you know!!

**Comment by michaelkrone** [comment]
Duplicate of #66
