### ISSUE TITLE
gitignore is missing on new generation.

### ISSUE THREAD

**Issue by TejasCMehta** [michaelkrone/generator-material-app#85]

**Comment by Stupidism** [comment]
v0.2.2 or develop branch?

**Comment by Stupidism** [comment]
only .gitignore or all dot-started files?

Maybe gulp with your filesystem can't copy hidden files

**Comment by TejasCMehta** [comment]
only `.gitignore` we also need bower_components and node_modules shuould be ignored, other then that `.jshintrc` `.jscsrc` `.bowerrc` is there

**Comment by TejasCMehta** [comment]
I added that  `.gitignore`  file manually and put below items as  ignore list.

`/node_modules`
`/build`
`/dist`
`.idea`
`.tmp`
`npm-debug.log`
`.sass-cache`

**Comment by Stupidism** [comment]
Some developers choose not to ignore bower_components.
