### ISSUE TITLE
gulp-protractor works

### ISSUE THREAD

**Issue by TejasCMehta** [michaelkrone/generator-material-app#88]
![image](https://cloud.githubusercontent.com/assets/5519037/15571556/1a2091d4-2359-11e6-8a3c-b07591af5bdd.png)

instead of
`"postinstall": "node node_modules/protractor/bin/webdriver-manager update"`

used
`"postinstall":"node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update"`

![image](https://cloud.githubusercontent.com/assets/5519037/15571612/6c411ccc-2359-11e6-8aef-822465678105.png)

This fixed the issue.

**Comment by Stupidism** [comment]
This is a known problem and should be fixed in develop. 
Because npm2 and npm3 build dependencies differently.

are you using npm2.x ?
run `npm -v` to check

**Comment by TejasCMehta** [comment]
npm version : `3.8.6`
