### ISSUE TITLE
Cannot save clientModelDoc

### ISSUE THREAD

**Issue by michaelkrone** [michaelkrone/generator-material-app#91]
When editing a clientModelDoc, the form does not get dirty and I cannot save the item.

**Comment by Stupidism** [comment]
Just edit?

**Comment by michaelkrone** [comment]
I think it was only edit

**Comment by Stupidism** [comment]
But I can't reappear this in my environment. I can edit normally.

**Comment by michaelkrone** [comment]
I will recheck.

**Comment by michaelkrone** [comment]
I just checked: I cannot edit a clientModelDoc (the save button will not get clickable).
Additionally, when editing the name and setting it back to the origin name the validation failed. There is the `remote-unique-ignore` attribute for this cases, which allows a value to be ignored.

**Comment by Stupidism** [comment]
I found the problem.
Last time I add doc for ng-messages, I only added properties on client side
