### ISSUE TITLE
Is is possible to have create modal be open from any state.

### ISSUE THREAD

**Issue by Stupidism** [michaelkrone/generator-material-app#95]
So that when you `create/edit` a resource A containing a property referenced to B, you click a `new button` aside the select dropdown and create a new B in a new popup modal with A.list.detail below `not changed` to B.list.

**Comment by michaelkrone** [comment]
You might either introduce a new route which opens and closes  a dialog on state change, but would need to inject the new created document per websocket, or encapsulate the dialog and creation logic inside a service which will give you the resulting new document as the result of the modal close call.
