### ISSUE TITLE
Error: Cannot find module '***/protractor/bin/webdriver-manager'

### ISSUE THREAD

**Issue by prabashbala** [michaelkrone/generator-material-app#97]
Error while running 'bower install & npm install'  to install the required dependencies. Error log below.

> 111332 verbose cwd /home/ubuntu/workspace/app
> 111333 error Linux 4.2.0-c9
> 111334 error argv "/home/ubuntu/.nvm/versions/node/v6.0.0/bin/node" "/home/ubuntu/.nvm/versions/node/v6.0.0/bin/npm" "install"
> 111335 error node v6.0.0
> 111336 error npm  v3.10.2
> 111337 error code ELIFECYCLE
> 111338 error app@0.0.0 postinstall: `node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update`
> 111338 error Exit status 1
> 111339 error Failed at the app@0.0.0 postinstall script 'node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update'.
> 111339 error Make sure you have the latest version of node.js and npm installed.
> 111339 error If you do, this is most likely a problem with the app package,
> 111339 error not with npm itself.
> 111339 error Tell the author that this fails on your system:
> 111339 error     node ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update
> 111339 error You can get information on how to open an issue for this project with:
> 111339 error     npm bugs app
> 111339 error Or if that isn't available, you can get their info via:
> 111339 error     npm owner ls app
> 111339 error There is likely additional logging output above.
> 111340 verbose exit [ 1, true ]

**Comment by Stupidism** [comment]
Change `gulp-protractor/node_modules/protractor/` in package.json to `protractor/`.
You'd best wait for next release...

**Comment by prabashbala** [comment]
Thanks , it worked.
